#!/usr/bin/env python3
"""Q4.5：卡片读数/原生键盘/弹簧静置，装饰轨真实晶体投影与像素软避让。"""
import argparse,json,os,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
sys.path.insert(0,str(ROOT/'tests'))
import headless as H
import sky_field_layer as V
BOOKS=[('saga','data/sample-saga.json'),('sanguo','data/cache/a935953b2678a80b352091d5.json'),('dafeng','data/cache/2ef47b2ecaa99a67352091d5.json')]
CARD=r"""(async function(){var G=CLApp.graph(),D=CLSkyGroupsShell.deck();D.fold(false);var big=CLApp.scene().skyInfo().sectors.slice().sort(function(a,b){return b.count-a.count;})[0];D.open(big.name);await W(500);var card=document.querySelector('.skg-card.is-open'),vp=document.querySelector('.skg-viewport'),box=vp.getBoundingClientRect();vp.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:box.right-4,clientY:box.top+box.height*.4}));await W(200);var moving=CLSkyCards3D.stats();await W(2400);var rest=CLSkyCards3D.stats();return {names:[].map.call(document.querySelectorAll('.skg-bar>.skd-card__name'),function(e){return {text:e.textContent,title:e.title,clipped:e.scrollWidth>e.clientWidth+1};}),roles:[].map.call(card.querySelectorAll('.skg-card__role'),function(e){return {text:e.textContent,title:e.title,nowrap:getComputedStyle(e).whiteSpace,clipped:e.scrollWidth>e.clientWidth+1};}),moving:moving,rest:rest,member:card.querySelector('.skg-card__name').textContent,counts:[G.characters.length,G.relations.length,G.events.length]};})()"""
FOCUS=r"""(function(){var b=document.querySelector('.skg-card.is-open .skg-card__name');b.focus();return {outline:getComputedStyle(b).outlineStyle,width:parseFloat(getComputedStyle(b).outlineWidth),key:b.textContent};})()"""
ORBIT=r"""(async function(){await W(2800);var S=CLApp.scene(),R=S.renderer,out={mode:CLSky.state().mode,name:CLSky.state().compass},b=S.crownScreenBounds(),st=CLSkyDeep.stats().orrery;out.link={actual:st.occlusion,expected:[(b.left+b.right)/2/innerWidth,(b.top+b.bottom)/2/innerHeight,(b.right-b.left)*.52/innerWidth,(b.bottom-b.top)*.52/innerHeight]};document.body.classList.add('skylab-still');await W(200);var objects=[];S.scene.traverse(function(o){if(o.geometry&&o.material&&o.material.uniforms&&o.material.uniforms.uOcclude)objects.push(o);});var centerA=new THREE.Vector3(),centerB=new THREE.Vector3();S.crownAnchor().getWorldPosition(centerA);objects.filter(function(o){return o.isMesh;})[0].parent.parent.getWorldPosition(centerB);out.centerError=centerA.distanceTo(centerB);out.tick=objects.filter(function(o){return o.isMesh;}).map(function(o){var a=o.geometry.attributes.aT.array;return {min:Math.min.apply(null,a),max:Math.max.apply(null,a),unique:new Set(a).size};});
var width=innerWidth,height=innerHeight,rt=new THREE.WebGLRenderTarget(width,height),isolated=new THREE.Scene(),pixels=new Uint8Array(width*height*4),oldRT=R.getRenderTarget(),color=R.getClearColor(new THREE.Color()).clone(),alpha=R.getClearAlpha(),u=objects[0].material.uniforms.uOcclude.value,save=u.clone(),keep=objects[0].material.uniforms.uOccKeep.value;objects.forEach(function(o){o.updateWorldMatrix(true,false);var c=o.isPoints?new THREE.Points(o.geometry,o.material):new THREE.Mesh(o.geometry,o.material);c.matrixAutoUpdate=false;c.matrix.copy(o.matrixWorld);c.frustumCulled=false;isolated.add(c);});
function read(){R.setRenderTarget(rt);R.setClearColor(0,0);R.clear();R.render(isolated,S.camera);R.readRenderTargetPixels(rt,0,0,width,height,pixels);var inside=0,outside=0,lit=0;for(var y=0;y<height;y++)for(var x=0;x<width;x++){var at=(y*width+x)*4,v=Math.max(pixels[at],pixels[at+1],pixels[at+2]),dx=(x/width-save.x)/save.z,dy=((1-y/height)-save.y)/save.w,d=dx*dx+dy*dy;if(d<.25)inside+=v;if(d>1.25)outside+=v;if(v>2)lit++;}return {inside:inside,outside:outside,lit:lit,error:R.getContext().getError()};}
try{out.soft=read();u.set(0,0,0,0);out.full=read();u.copy(save);out.views=[{soft:out.soft,full:out.full}];
/* 没有穿过晶体核心的默认机位不能提供遮挡正样本：沿真实控制器允许的绕心机位继续量，保留非空像素断言。 */
var base=S.camera.position.clone().sub(S.controls.target),angles=[.6,-.6,1.2,-1.2,.4,-.4,.75,-.75];
for(var vi=0;vi<angles.length&&out.full.inside<=100;vi++){var axis=new THREE.Vector3(vi<4?0:1,vi<4?1:0,0);S.camera.position.copy(S.controls.target).add(base.clone().applyAxisAngle(axis,angles[vi]));S.controls.update();await W(250);save.copy(u);objects.forEach(function(o,i){o.updateWorldMatrix(true,false);isolated.children[i].matrix.copy(o.matrixWorld);});out.soft=read();u.set(0,0,0,0);out.full=read();u.copy(save);out.views.push({axis:vi<4?'Y':'X',angle:angles[vi],soft:out.soft,full:out.full});}
}finally{u.copy(save);R.setRenderTarget(oldRT);R.setClearColor(color,alpha);rt.dispose();}
S.setDegrade(2);await W(150);out.low=CLSkyDeep.stats().orrery;S.setDegrade(0);out.counts=[CLApp.graph().characters.length,CLApp.graph().relations.length,CLApp.graph().events.length];return out;})()"""
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--base',default='http://127.0.0.1:8765');ap.add_argument('--books',default='saga,sanguo,dafeng');ap.add_argument('--sizes',default='1440x900,390x844');ap.add_argument('--out',default='/tmp/xingxi-ui-finish');a=ap.parse_args();outdir=Path(a.out);outdir.mkdir(parents=True,exist_ok=True);passed=total=0
 if os.environ.get('CL_GPU')!='1':raise SystemExit('CL_GPU=1 required')
 for book,data in BOOKS:
  if book not in a.books.split(','):continue
  for size in a.sizes.split(','):
   V.BOOK=data;p=V.Page(a.base,size)
   try:
    p.ws.call('Emulation.setFocusEmulationEnabled',enabled=True)
    card=p.ev(CARD) or {};p.ws.call('Input.dispatchKeyEvent',type='keyDown',key='Tab',code='Tab',windowsVirtualKeyCode=9);p.ws.call('Input.dispatchKeyEvent',type='keyUp',key='Tab',code='Tab',windowsVirtualKeyCode=9);focus=p.ev(FOCUS) or {};p.ws.call('Input.dispatchKeyEvent',type='keyDown',key='Enter',code='Enter',windowsVirtualKeyCode=13,text='\r',unmodifiedText='\r');p.ws.call('Input.dispatchKeyEvent',type='keyUp',key='Enter',code='Enter',windowsVirtualKeyCode=13);orb=p.ev(ORBIT) or {};health=H.post_health(p.ws,[])
    result={'card':card,'focus':focus,'orbit':orb,'healthExit':health};(outdir/(book+'-'+size+'.json')).write_text(json.dumps(result,ensure_ascii=False,indent=2))
    link=orb.get('link',{});soft=orb.get('soft',{});full=orb.get('full',{});rest=card.get('rest',{})
    checks=[('health',health==0),('group names retain width and full titles',bool(card.get('names')) and all(x['title']==x['text'] and not x['clipped'] for x in card['names'])),('identities wrap and remain complete',bool(card.get('roles')) and all(x['title']==x['text'] and x['nowrap']=='normal' and not x['clipped'] for x in card['roles'])),('shared spring settles into clear flat text',card.get('moving',{}).get('depth',0)>.01 and abs(rest.get('depth',99))<.005 and not rest.get('live')),('native Enter activates the real member, focus is visible',focus.get('outline')!='none' and focus.get('width',0)>0 and orb.get('mode')=='compass' and orb.get('name')==focus.get('key')),('crystal projection drives soft occlusion',bool(link.get('actual')) and max(abs(x-y) for x,y in zip(link['actual'],link['expected']))<.01),('orbit center follows the moving crystal',orb.get('centerError',99)<.001),('three rings retain a monotonic full tick range',len(orb.get('tick',[]))==3 and all(x['min']==0 and x['max']==1 and x['unique']>=100 for x in orb['tick'])),('real pixels are softened inside crystal, outer orbit stays',full.get('inside',0)>100 and soft.get('inside',999999)<full.get('inside',0)*.35 and full.get('outside',0)>100 and .95<soft.get('outside',0)/full['outside']<1.05 and soft.get('lit',0)>100 and soft.get('error',-1)==full.get('error',-1)==0),('low and reduced keep the crystal soft mask',orb.get('low',{}).get('tier')=='low' and orb['low'].get('occludeKeep')==.16 and (orb['low'].get('occlusion') or [0,0,0])[2]>0),('data preserved',bool(card.get('counts')) and card['counts']==orb.get('counts'))]
    for name,ok in checks:total+=1;passed+=bool(ok);print(('PASS ' if ok else 'FAIL ')+book+' '+size+' '+name,flush=True)
    if any(not ok for _,ok in checks):print(json.dumps(result,ensure_ascii=False)[:4000],flush=True)
   finally:p.close()
 print('SKY-UI-FINISH '+('OK' if passed==total and total else 'FAIL')+' · '+str(passed)+'/'+str(total));return 0 if passed==total and total else 1
if __name__=='__main__':raise SystemExit(main())
