/* Castline · constellation-reading.js · isolated semantic reading surface */
(function (g) {
  'use strict';
  function esc(v) { return String(v == null ? '' : v).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
  function arr(v) { return Array.isArray(v) ? v : []; }
  function label(v) { return v == null || v === '' ? '未提供' : String(v); }
  function byId(xs, id) { for (var i = 0; i < xs.length; i++) if (xs[i].id === id) return xs[i]; return null; }
  function source(r) { if (r.sourceType || r.sourceRef) return (r.sourceType || '来源') + (r.sourceRef ? ' · ' + r.sourceRef : '（待定位）'); return '关系来源未提供'; }
  function relationLine(r) {
    return '<li class="clr-relation' + (r.dark ? ' is-dark' : '') + '" data-relation-id="' + esc(r.id) + '"><button class="clr-relation__link" type="button" data-action="relation"><span class="clr-rel-names">' + esc(r.aName) + ' ↔ ' + esc(r.bName) + '</span><span class="clr-rel-kind">' + esc(r.kind) + '</span><span class="clr-rel-meta">强度 ' + esc(label(r.strength)) + ' · ' + esc(source(r)) + (r.stage != null ? ' · 阶段 ' + esc(r.stage) : ' · 阶段未提供') + (r.unresolved ? ' · 未解析：' + esc(r.unresolvedReason) : '') + '</span><span class="clr-rel-events">' + (r.desc ? esc(r.desc) : '关系说明未提供') + (r.hidden && r.hidden !== '—' ? ' · 暗线说明：' + esc(r.hidden) : '') + '<br>' + (r.eventRefs && r.eventRefs.length ? '来源引用 ' + r.eventRefs.map(function (e) { return esc((e.kind || '引用') + ':' + (e.label || e.value) + (e.resolved ? '' : '（未解析：' + (e.reason || '未知') + '）')); }).join('、') : '来源引用未提供；共同出场不等于出处。') + '</span></button></li>';
  }
  function eventLines(r) {
    if (!r.eventRefs || !r.eventRefs.length) return '<span class="clr-unknown">来源引用未提供；共同出场不等于出处。</span>';
    return '<span class="clr-event-label">来源引用</span>' + r.eventRefs.map(function (e) { return e.resolved ? '<button class="clr-event" type="button" data-event-ref="' + esc(JSON.stringify(e)) + '" data-action="event">' + esc(e.label || e.value) + '</button>' : '<span class="clr-event clr-unresolved">' + esc(e.label || e.value) + '（未解析：' + esc(e.reason || '未知') + '）</span>'; }).join('');
  }
  function render(model) {
    model = model || { groups: [], people: [], relations: [], bridges: [], aggregates: {}, capabilities: {}, warnings: [] };
    var people = arr(model.people), groups = arr(model.groups), rels = arr(model.relations), bridges = arr(model.bridges), agg = model.aggregates || {};
    var total = agg.relationCount == null ? rels.length : agg.relationCount;
    var html = '<section class="clr-reading" data-clr-reading="1" aria-label="星座世界关系阅读"><header class="clr-header"><div class="clr-eyebrow">CONSTELLATION READING · 世界关系</div><div class="clr-counts"><span>群体 <b>' + esc(agg.groupCount == null ? groups.length : agg.groupCount) + '</b></span><span>人物 <b>' + esc(agg.peopleCount == null ? people.length : agg.peopleCount) + '</b></span><span>关系记录 <b>' + esc(total) + '</b></span><span>已解析 <b>' + esc(agg.validRelationCount || 0) + '</b></span><span>未解析 <b>' + esc(agg.unresolvedRelationCount || 0) + '</b></span><span>无效 <b>' + esc(agg.invalidRelationCount || 0) + '</b></span><span>暗线 <b>' + esc(agg.darkRelationCount || 0) + '</b></span></div></header>';
    html += '<div class="clr-capabilities"><span>地理：不支持</span><span>阶段标签：' + (model.capabilities && model.capabilities.stageLabels ? '可用' : '未提供') + '</span><span>阶段变化：不支持</span><span>来源事件：' + (model.capabilities && model.capabilities.eventRefs ? '部分可用' : '未提供') + '</span></div><label class="clr-search">搜索群体 / 人物 / 关系 <input type="search" data-action="search" placeholder="名称、别名、类型或来源" /><span class="clr-search-count" data-search-count>' + people.length + ' 人物 · ' + groups.length + ' 群体 · ' + total + ' 关系</span><button type="button" data-action="clear-search">清除</button></label>';
    html += '<div class="clr-groups"><h3>群体与成员</h3><div class="clr-group-list">' + groups.map(function (gr) { var mem = people.filter(function (p) { return p.groupIds.indexOf(gr.id) >= 0; }); return '<details class="clr-group" data-group-id="' + esc(gr.id) + '"><summary><span class="clr-group-name">' + esc(gr.name) + '</span><span class="clr-group-count">' + mem.length + ' 人 · ' + esc(gr.stance) + '</span><span class="clr-group-source">' + esc(gr.source) + '</span></summary><div class="clr-group-body"><p>' + esc(gr.brief || '群体说明未提供。') + '</p><button type="button" class="clr-camp-link" data-action="camp">查看群体</button><ul class="clr-people">' + mem.map(function (p) { return '<li data-person-id="' + esc(p.id) + '"><button type="button" class="clr-person" data-action="character"' + (!p.navigable ? ' disabled title="重名待确认"' : '') + '><span>' + esc(p.name) + '</span><small>' + (!p.navigable ? '重名待确认' : (p.isolated ? '无可解析关系' : '')) + (p.unresolvedAssociations ? ' · 未解析关联 ' + p.unresolvedAssociations : '') + '</small></button></li>'; }).join('') + '</ul></div></details>'; }).join('') + '</div></div>';
    html += '<div class="clr-bridges"><h3>跨群桥接</h3>' + (bridges.length ? '<ul>' + bridges.map(function (b) { var ppl = (b.peopleIds || []).map(function (pid) { var p = byId(people, pid); return p ? '<li data-person-id="' + esc(p.id) + '"><button type="button" class="clr-person clr-bridge-person" data-action="character"' + (!p.navigable ? ' disabled title="重名待确认"' : '') + '>' + esc(p.name) + '</button></li>' : ''; }).join(''); return '<li><span>' + esc((b.groupNames || b.groupIds).join(' ↔ ')) + '</span><ul class="clr-bridge-people">' + ppl + '</ul><small>' + b.relationIds.length + ' 条关系</small></li>'; }).join('') + '</ul>' : '<p class="clr-unknown">未提供跨群桥接。</p>') + '</div>';
    html += '<div class="clr-relations"><h3>关系与暗线 <span>' + esc(total) + ' 条关系记录</span></h3><p class="clr-legend">实线/暗线只按原始关系记录；引导线与星座字形骨架不计入此数。</p><ul>' + rels.map(relationLine).join('') + '</ul></div><div class="clr-evidence" tabindex="-1"><h3>关系出处</h3><div data-evidence-host="1"><p class="clr-unknown">选择一条关系查看来源引用。</p></div></div>';
    if (model.warnings && model.warnings.length) html += '<aside class="clr-warnings"><h3>能力边界</h3><ul>' + model.warnings.map(function (w) { return '<li>' + esc(w) + '</li>'; }).join('') + '</ul></aside>';
    return html + '</section>';
  }
  function mount(host, options) {
    options = options || {}; var root = host && host.nodeType ? host : null, model = options.model || {}, disposed = false;
    if (!root) return function () {};
    if (typeof root.__clrDispose === 'function') root.__clrDispose();
    root.innerHTML = render(model); var surface = root.querySelector('[data-clr-reading]'); if (!surface) return function () {};
    root.__clrDispose = function () { if (disposed) return; disposed = true; surface.removeEventListener('click', click); surface.removeEventListener('input', input); if (root.contains(surface)) root.removeChild(surface); root.__clrDispose = null; };
    function findRelation(id) { return arr(model.relations).filter(function (r) { return r.id === id; })[0] || null; }
    function click(e) { if (disposed) return; var el = e.target.closest && e.target.closest('[data-action]'); if (!el || !surface.contains(el)) return; var action = el.getAttribute('data-action');
      if (action === 'clear-search') { var inputEl = surface.querySelector('[data-action="search"]'); if (inputEl) { inputEl.value = ''; input({ target: inputEl }); inputEl.focus(); } }
      else if (action === 'character' && !el.disabled && options.onCharacter) { var li = el.closest('[data-person-id]'), p = li && byId(model.people || [], li.getAttribute('data-person-id')); if (p) options.onCharacter({ personId: p.personId || p.id, name: p.name, stable: !!p.personId }); }
      else if (action === 'camp' && options.onCamp) { var gr = el.closest('[data-group-id]'); if (gr) options.onCamp(gr.getAttribute('data-group-id')); }
      else if (action === 'relation') { var row = el.closest('[data-relation-id]'), rel = row && findRelation(row.getAttribute('data-relation-id')), evHost = surface.querySelector('[data-evidence-host]'); Array.prototype.forEach.call(surface.querySelectorAll('.clr-relation.is-selected'), function (x) { x.classList.remove('is-selected'); }); if (row) row.classList.add('is-selected'); if (evHost && rel) { evHost.innerHTML = '<p class="clr-evidence-title">' + esc(rel.aName + ' ↔ ' + rel.bName + ' · ' + rel.kind) + '</p><p>' + esc(rel.desc || '关系说明未提供') + (rel.hidden && rel.hidden !== '—' ? ' · 暗线说明：' + esc(rel.hidden) : '') + '</p><p class="clr-evidence-source">来源：' + esc(source(rel)) + '</p><div class="clr-evidence-links">' + eventLines(rel) + '</div><button type="button" data-action="return-relation">返回关系记录</button>'; var ev = surface.querySelector('.clr-evidence'); if (ev) { ev.focus(); ev.scrollIntoView({ block: 'nearest' }); } } if (options.onRelation && rel) options.onRelation(rel); }
      else if (action === 'return-relation') { var rels = surface.querySelector('.clr-relations'), selected = surface.querySelector('.clr-relation.is-selected .clr-relation__link'); if (rels) rels.scrollIntoView({ block: 'nearest' }); if (selected) selected.focus(); }
      else if (action === 'event' && options.onEvent) { var ref; try { ref = JSON.parse(el.getAttribute('data-event-ref')); } catch (_) { ref = null; } if (ref && ref.resolved) options.onEvent({ eventId: ref.eventId, order: ref.order, index: ref.index, eventOrder: ref.order, eventIndex: ref.index, resolved: true, kind: ref.kind, value: ref.value }); }
    }
    function input(e) { if (!e.target.matches || !e.target.matches('[data-action="search"]')) return; var q = String(e.target.value || '').trim().toLowerCase(), visibleGroups = 0, visiblePeople = 0, visibleRelations = 0; Array.prototype.forEach.call(surface.querySelectorAll('[data-group-id]'), function (n) { var gid = n.getAttribute('data-group-id'), gr = (model.groups || []).filter(function (x) { return x.id === gid; })[0], mem = (model.people || []).filter(function (p) { return p.groupIds.indexOf(gid) >= 0; }), groupHay = [gr && gr.name, gr && gr.brief].join(' ').toLowerCase(), groupHit = !q || groupHay.indexOf(q) >= 0, anyPerson = false; n.hidden = !!q && !groupHit; if (!n.hidden) { visibleGroups++; if (q) n.open = true; } Array.prototype.forEach.call(n.querySelectorAll('[data-person-id]'), function (li) { var p = byId(model.people || [], li.getAttribute('data-person-id')), ph = p ? [p.name].concat(p.aliases || []).join(' ').toLowerCase() : ''; var personHit = !!q && ph.indexOf(q) >= 0; if (personHit) anyPerson = true; li.hidden = !!q && !groupHit && !personHit; if (!li.hidden) visiblePeople++; }); if (q && anyPerson && n.hidden) { n.hidden = false; visibleGroups++; n.open = true; } }); Array.prototype.forEach.call(surface.querySelectorAll('[data-relation-id]'), function (n) { var r = findRelation(n.getAttribute('data-relation-id')), hay = r ? [r.kind, r.desc, r.note, r.sourceType, r.sourceRef, r.aName, r.bName].join(' ').toLowerCase() : ''; n.hidden = !!q && hay.indexOf(q) < 0; if (!n.hidden) visibleRelations++; }); var counter = surface.querySelector('[data-search-count]'); if (counter) counter.textContent = q ? visibleGroups + '/' + (model.groups || []).length + ' 群体 · ' + visiblePeople + '/' + (model.people || []).length + ' 人物 · ' + visibleRelations + '/' + (model.relations || []).length + ' 关系' + (visibleGroups + visiblePeople + visibleRelations ? '' : ' · 无匹配') : (model.people || []).length + '/' + (model.people || []).length + ' 人物 · ' + (model.groups || []).length + '/' + (model.groups || []).length + ' 群体 · ' + (model.relations || []).length + '/' + (model.relations || []).length + ' 关系'; }
    surface.addEventListener('click', click); surface.addEventListener('input', input); return root.__clrDispose;
  }
  g.CLConstellationReading = { render: render, mount: mount };
})(typeof window !== 'undefined' ? window : this);
