#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Castline · 色板 → CSS token 生成器（gen_tokens · 零依赖 · 不启浏览器）

星渊宪法 G1：js/palette.js 是全项目唯一的语义色真相。
本脚本从 palette.js 提取事件色 / 阵营色 / 语义色 / 深渊灰阶，
生成 app.css 头部的「受保护区」:root 变量块 —— CSS 侧不再手写色值。

用法：
  python3 -s scripts/gen-tokens.py            # 校验 app.css 受保护区与 palette.js 一致
  python3 -s scripts/gen-tokens.py --write    # 用最新生成块覆盖 app.css 受保护区
  python3 -s scripts/gen-tokens.py --stdout   # 只打印生成块，不碰文件

退出码：0 一致 / 1 不一致或失败
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PALETTE_JS = os.path.join(ROOT, 'js', 'palette.js')
APP_CSS = os.path.join(ROOT, 'css', 'app.css')

GUARD_OPEN = '/* === ABYSS TOKENS · generated by scripts/gen-tokens.py — DO NOT EDIT === */'
GUARD_CLOSE = '/* === end ABYSS TOKENS === */'


def hex6(v):
    if isinstance(v, int):
        return format(v, '06x')
    return ('000000' + format(int(v, 16), '06x'))[-6:]


def parse_js_arrays(src):
    """从 palette.js 源码里正则提取顶层数组 / 对象字面量（ES5，无嵌套花括号陷阱）。"""
    out = {}

    def grab(name, pattern, cast):
        m = re.search(r'var\s+' + name + r'\s*=\s*' + pattern, src, re.S)
        if not m:
            raise SystemExit('FAIL · palette.js 找不到 var %s' % name)
        out[name] = cast(m.group(1))

    def arr(s):
        return re.findall(r"'([^']*)'|0x([0-9a-fA-F]{6})|#([0-9a-fA-F]{6})", s)

    def arr_hex(s):
        return [int(h, 16) for _, h, _ in arr(s)]

    def obj_int(s):
        d = {}
        for k, h in re.findall(r"([A-Za-z0-9_]+):\s*0x([0-9a-fA-F]{6})", s):
            d[k] = int(h, 16)
        return d

    grab('CSS', r'\[([^\]]*)\]', arr)
    grab('CAMP_CSS', r'\[([^\]]*)\]', lambda s: re.findall(r"'([^']*)'", s))
    grab('CAMP_HEX', r'\[([^\]]*)\]', arr_hex)
    grab('SEM', r'\{\s*([^}]*)\}', obj_int)
    grab('GREY', r'\{\s*([^}]*)\}', obj_int)
    return out


def gen_block(css_list, camp_css_list, camp_hex_list, sem, grey):
    lines = [GUARD_OPEN]
    lines.append(':root{')
    # 事件色
    kinds = ['高燃', '转折', '抉择', '冲突', '关系', '领悟', '日常']
    for i, c in enumerate(css_list):
        lines.append('  --evt-%d:%s;' % (i, c))
    lines.append('  /* 事件色命名映射（语义 → 序号） */')
    for i, k in enumerate(kinds):
        lines.append('  --evt-%s:var(--evt-%d);' % (k, i))
    # 阵营色
    camps = ['主角方', '盟友', '中立', '摇摆', '对立']
    for i, c in enumerate(camp_css_list[:-1]):
        lines.append('  --camp-%d:%s;' % (i, c))
    for i, k in enumerate(camps):
        lines.append('  --camp-%s:var(--camp-%d);' % (k, i))
    lines.append('  --camp-散星:%s;' % camp_css_list[-1])
    # 语义色
    for k, v in sem.items():
        lines.append('  --sem-%s:#%s;' % (k, hex6(v)))
    # 深渊灰阶
    for k, v in grey.items():
        lines.append('  --grey-%s:#%s;' % (k, hex6(v)))
    lines.append('  /* 兼容别名（旧代码直接引用，禁止再手写色值） */')
    lines.append('  --bg:var(--grey-bg);')
    lines.append('  --ink:var(--grey-ink);')
    lines.append('  --ink-2:var(--grey-s5);')
    lines.append('  --ink-3:var(--grey-s4);')
    lines.append('  --signal:var(--sem-signal);')
    lines.append('  --signal-2:var(--sem-signalHi);')
    lines.append('  --violet:var(--sem-violet);')
    lines.append('  --violet-2:var(--sem-violetLo);')
    lines.append('  --mint:var(--sem-mint);')
    lines.append('  --cyan:var(--sem-signal);')
    lines.append('  --hot:var(--sem-hot);')
    lines.append('}')
    lines.append(GUARD_CLOSE)
    return '\n'.join(lines) + '\n'


def extract_guard(css):
    m = re.search(re.escape(GUARD_OPEN) + r'.*?' + re.escape(GUARD_CLOSE), css, re.S)
    return m.group(0) if m else None


def main():
    write = '--write' in sys.argv
    stdout = '--stdout' in sys.argv
    src = open(PALETTE_JS, encoding='utf-8').read()
    d = parse_js_arrays(src)
    m_css = re.search(r'var\s+CSS\s*=\s*\[([^\]]*)\]', src)
    css_list = re.findall(r"'([^']*)'", m_css.group(1))
    block = gen_block(css_list, d['CAMP_CSS'], d['CAMP_HEX'], d['SEM'], d['GREY'])

    if stdout:
        sys.stdout.write(block)
        return 0

    css = open(APP_CSS, encoding='utf-8').read()
    old = extract_guard(css)
    if old is None:
        print('FAIL · app.css 没有受保护区（%s）' % GUARD_OPEN)
        return 1
    if old == block.rstrip('\n'):
        print('OK · app.css 受保护区与 palette.js 一致')
        return 0
    if not write:
        print('MISMATCH · app.css 受保护区与 palette.js 不一致（用 --write 更新）')
        return 1
    open(APP_CSS, 'w', encoding='utf-8').write(css.replace(old, block.rstrip('\n')))
    print('WROTE · app.css 受保护区已更新')
    return 0


if __name__ == '__main__':
    sys.exit(main())
